name: Deploy T-shop Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "Users/ZiboMatiwaza/final Devops/T-shop-iac/**"

env:
  RESOURCE_GROUP: Ecommerce-RG
  LOCATION: southafricanorth

jobs:
  deploy-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --template-file "Users/ZiboMatiwaza/final Devops/T-shop-iac/main.bicep" \
            --parameters "Users/ZiboMatiwaza/final Devops/T-shop-iac/parameters.json" \
            --name tshop-deployment-${{ github.run_number }}
