name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template to Ecommerce-RG
        run: |
          az deployment group create \
            --resource-group Ecommerce-RG \
            --template-file "./Users/ZiboMatiwaza/final Devops/T-shop-iac/main.bicep" \
            --parameters "@./Users/ZiboMatiwaza/final Devops/T-shop-iac/parameters.json"
